export const LOGIN_START='LOGIN_START';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILED='LOGIN_FAILED';
export const SIGNUP_FAILED='SIGNUP_FAILED';
export const SIGNUP_SUCCESS='SIGNUP_SECCESS';
export const SIGNUP_START='START';
