export const LOGIN_START='LOGIN_START';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILED='LOGIN_FAILED';
export const SIGNUP_FAILED='SIGNUP_FAILED';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const SIGNUP_START='SIGNUP_START';
export const AUTHENTICATE_USER='AUTHENTICATE_USER';
export const LOG_OUT='LOG_OUT';
export const FETCH_POST='FETCH_POST';
export const ADD_POST='ADD_POST';
export const EDIT_PROFILE='EDIT_PROFILE';
export const USER_PROFILE='USER_PROFILE';
export const SEARCH_RESULT_START='SEARCH_RESULT_START';
export const SEARCH_RESULT_SUCCESS='SEARCH_RESULT_SUCCESS';
export const SEARCH_RESULT_FAILED='SEARCH_RESULT_FAILED';
export const FETCH_FRIEND='FETCH_FRIEND';
export const FETCH_USERS='FETCH_USERS';
export const FETCH_ALUMINI='FETCH_ALUMINI';




